# Generated by Django 5.2.2 on 2025-06-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymen_method',
            new_name='payment_method',
        ),
    ]
